[tool.poetry]
name = "laba4"
version = "0.1.0"
description = ""
authors = ["Unfectum <roma509000@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
Flask = "^1.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
